name: scmodal_scviva
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=4_kmp_llvm
  - absl-py=2.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anndata=0.11.4=pyhd8ed1ab_0
  - anyio=4.10.0=py310h06a4308_0
  - aom=3.9.1=hac33072_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310hee96239_0
  - array-api-compat=1.12.0=pyhe01879c_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=py310h06a4308_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=py310h06a4308_2
  - babel=2.16.0=py310h06a4308_0
  - beautifulsoup4=4.13.5=py310h06a4308_0
  - bleach=6.2.0=py310h06a4308_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py310hea6c23e_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=2.0.0=py310h34a4b09_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - chex=0.1.90=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-version=12.9=h4f385c5_3
  - cudnn=8.9.7.29=h092f7fd_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docrep=0.3.2=pyh44b312d_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - etils=1.12.2=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.19.1=pyhd8ed1ab_0
  - flax=0.10.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glib=2.86.0=he175458_0
  - glib-tools=2.86.0=hf516916_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_1
  - graphite2=1.3.14=hecca717_2
  - grpcio=1.62.2=py310h1b8f574_0
  - gseapy=1.1.10=py310hec43fc7_0
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - h11=0.16.0=py310h06a4308_1
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.14.0=nompi_py310h4aa865e_101
  - harfbuzz=12.1.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_1
  - humanize=4.13.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipython_pygments_lexers=1.1.1=py310h06a4308_0
  - ipywidgets=8.1.7=py310h06a4308_0
  - jax=0.4.31=pyhd8ed1ab_0
  - jaxlib=0.4.31=cpu_py310h63146f5_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.9.25=py310h06a4308_0
  - jsonschema=4.25.0=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - jupyter=1.1.1=py310h06a4308_0
  - jupyter-lsp=2.2.5=py310h06a4308_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=py310h06a4308_0
  - jupyter_server=2.16.0=py310h06a4308_0
  - jupyter_server_terminals=0.5.3=py310h06a4308_0
  - jupyterlab=4.4.7=py310h06a4308_0
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.28.0=py310h06a4308_0
  - jupyterlab_widgets=3.0.15=py310h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=36_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=36_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_4
  - libclang13=21.1.0=default_h746c552_1
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcufft=11.4.1.4=h5888daf_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.7.5.82=h9ab20c4_1
  - libcusparse=12.5.10.65=h5888daf_1
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=36_h47877c9_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmagma=2.7.2=h173bb3b_2
  - libmagma_sparse=2.7.2=h173bb3b_3
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.9.86=h5888daf_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_2
  - libopengl-devel=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libtorch=2.1.2=cuda120_he0d6596_304
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning=2.5.5=pyhd8ed1ab_0
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=21.1.2=h4922eb0_3
  - llvmlite=0.45.1=py310hee1c697_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib=3.8.4=py310hff52083_2
  - matplotlib-base=3.8.4=py310hef631a5_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.2=py310h06a4308_0
  - mkl=2023.2.0=ha770c72_50498
  - ml-collections=1.0.0=pyh29332c3_0
  - ml_dtypes=0.5.1=py310h0158d43_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py310h03d9f68_1
  - mudata=0.3.2=pyhd8ed1ab_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=py310h06a4308_0
  - nbconvert=7.16.6=py310h06a4308_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbconvert-pandoc=7.16.6=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - nccl=2.27.7.1=h49b9d9a_3
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook=7.4.5=py310h06a4308_0
  - notebook-shim=0.2.4=py310h06a4308_0
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - numba=0.62.1=py310h3477d8a_0
  - numpy=1.26.4=py310hb13e2d6_0
  - numpyro=0.19.0=pyhd8ed1ab_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openpyxl=3.1.5=py310h05b0c27_2
  - openssl=3.5.4=h26f9b46_0
  - opt-einsum=3.4.0=hd8ed1ab_1
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optax=0.2.6=pyhd8ed1ab_0
  - orbax-checkpoint=0.6.4=pyhd8ed1ab_1
  - overrides=7.7.0=py310h06a4308_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py310h06a4308_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310h6557065_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - protobuf=4.25.3=py310h0e2eeba_1
  - psutil=7.1.0=py310h7c4b9e2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=h9a8bead_2
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyopengl=3.1.10=pyha804496_2
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.11=py310h046fae5_2
  - pyqt5-sip=12.17.0=py310hea6c23e_2
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.9.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=hd6af730_0_cpython
  - python-annoy=1.17.3=py310hea6c23e_3
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.20.0=py310h06a4308_0
  - python-json-logger=3.2.1=py310h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.1.2=cuda120_py310h7891b24_304
  - pytorch-lightning=2.5.5=pyh2a12c56_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - pyzmq=27.1.0=py310h4f33d48_0
  - qt-main=5.15.15=h3a7ef08_5
  - qtconsole=5.7.0=py310h06a4308_0
  - qtpy=2.4.3=py310h06a4308_0
  - rav1e=0.7.1=h8fae777_3
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8c095d6_2
  - referencing=0.30.2=py310h06a4308_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rich=14.1.0=pyhe01879c_0
  - rpds-py=0.28.0=py310h498d7c9_0
  - scanpy=1.11.4=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h228f341_0
  - scipy=1.15.2=py310h1d65ade_0
  - scvi-tools=1.3.3=pyhd8ed1ab_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.2=py310h06a4308_1
  - session-info2=0.2.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py310hea6c23e_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sparse=0.17.0=pyhcf101f3_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310hf779ad0_1
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hb60516a_3
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310hed992bd_3
  - tensorstore=0.1.65=py310h55c8a0d_1
  - terminado=0.18.1=py310h06a4308_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=py310h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchaudio=2.1.2=py310_cpu
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchvision=0.16.1=cuda120py310he032570_3
  - tornado=6.5.2=py310h7c4b9e2_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.9.post2=py310hff52083_0
  - unicodedata2=16.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=py310h06a4308_0
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py310h139afa4_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiobotocore==2.25.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - botocore==1.40.49
      - click==8.3.0
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2024.5.3
      - datashader==0.18.2
      - fasteners==0.20
      - frozenlist==1.8.0
      - geopandas==1.1.1
      - imageio==2.37.0
      - jmespath==1.0.1
      - lazy-loader==0.4
      - locket==1.0.0
      - multidict==6.7.0
      - multiscale-spatial-image==2.0.3
      - numcodecs==0.13.1
      - ome-zarr==0.11.1
      - param==2.2.1
      - partd==1.4.2
      - pims==0.7
      - pooch==1.8.2
      - propcache==0.4.1
      - pyarrow==22.0.0
      - pyct==0.6.0
      - pyogrio==0.11.1
      - pyproj==3.7.1
      - rpy2==3.6.4
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - s3fs==2025.9.0
      - scikit-image==0.25.2
      - shapely==2.1.2
      - slicerator==1.1.0
      - spatial-image==1.2.3
      - spatialdata==0.5.0
      - tifffile==2025.5.10
      - tzlocal==5.3.1
      - wrapt==1.17.3
      - xarray-dataclass==3.0.0
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.22.0
      - zarr==2.18.3
prefix: /home/keerthana/anaconda3/envs/scmodal_scviva
